In [2]:
file_name_train='trainIdx2_matrix.txt'
fTrain=open(file_name_train, 'r')
lines = fTrain.readlines()
lines

['199808|248969|90\n',
 '199808|2663|90\n',
 '199808|28341|90\n',
 '199808|42563|90\n',
 '199808|59092|90\n',
 '199808|64052|90\n',
 '199808|69022|90\n',
 '199808|77710|90\n',
 '199808|79500|90\n',
 '199808|82317|90\n',
 '199808|97326|90\n',
 '199808|100987|90\n',
 '199808|119186|90\n',
 '199808|152077|90\n',
 '199808|154852|90\n',
 '199808|165161|90\n',
 '199808|181190|90\n',
 '199808|182018|90\n',
 '199808|186306|90\n',
 '199808|200141|90\n',
 '199808|206388|90\n',
 '199808|206862|90\n',
 '199808|210480|90\n',
 '199808|211701|90\n',
 '199808|224444|90\n',
 '199808|231613|90\n',
 '199808|231934|90\n',
 '199808|237425|90\n',
 '199808|270557|90\n',
 '199808|275191|90\n',
 '199808|295381|90\n',
 '199808|77904|90\n',
 '199808|158282|90\n',
 '199808|173467|90\n',
 '199808|176858|70\n',
 '199809|23717|90\n',
 '199809|33269|90\n',
 '199809|33722|80\n',
 '199809|43767|90\n',
 '199809|45979|90\n',
 '199809|49876|90\n',
 '199809|68667|80\n',
 '199809|70401|90\n',
 '199809|70850|90\n',
 '199809|

In [3]:
file_name_test='testTrack_hierarchy.txt'
fTest= open(file_name_test, 'r')
linesTest = fTest.readlines()
linesTest

['199810|208019|209288|None\n',
 '199810|74139|277282|271146|113360|173467|173655|192976|146792|48505|133159\n',
 '199810|9903|None|None|33722|123396|79926|73523\n',
 '199810|242681|190640|244574|61215|17453|274088\n',
 '199810|18515|146344|33168|19913|48505|154024\n',
 '199810|105760|93458|11616|131552|173467|48505|133159\n',
 '199812|276940|201356|163237|287681\n',
 '199812|142408|112725|275191|158282|173467|242383|207648|48505|133159\n',
 '199812|130023|226816|275191|158282|242383|207648|19913\n',
 '199812|29189|104694|211701|158282|173467|81520|139095|48505|133159\n',
 '199812|223706|101750|128069|158282|207648|279143\n',
 '199812|211361|127464|19438|77904\n',
 '199813|188441|195380|22935|33722|224280\n',
 '199813|20968|None|None|61215|34486|274088|228419|218185|146103|55447|30949|67098\n',
 '199813|21571|217069|89183|71345\n',
 '199813|79640|43214|232859|61215|199606|18161|148278|88853\n',
 '199813|184173|292343|196404|33722|271945|224280\n',
 '199813|111874|117381|231280|131552|1

In [4]:
len(linesTest)

120000

In [36]:
import numpy

file_name_test='testTrack_hierarchy.txt'
file_name_train='trainIdx2_matrix.txt'
output_file= 'output1.txt'

fTest= open(file_name_test, 'r')
fTrain=open(file_name_train, 'r')
Trainline= fTrain.readline()
fOut = open(output_file, 'w')

trackID_vec=[0]*6
albumID_vec=[0]*6
artistID_vec=[0]*6

gen1_vec=[0]*6
gen2_vec=[0]*6
gen3_vec=[0]*6
gen4_vec=[0]*6
gen5_vec=[0]*6
gen6_vec=[0]*6
gen7_vec=[0]*6
lastUserID=-1

user_rating_inTrain=numpy.zeros(shape=(6,9))

for line in fTest:
    arr_test=line.strip().split('|')
    userID= arr_test[0]
    trackID= arr_test[1]
    albumID= arr_test[2]
    artistID=arr_test[3]
    
    gen1_ID = gen2_ID = gen3_ID = gen4_ID = gen5_ID = gen6_ID = gen7_ID = 0
    
    if len(arr_test) >=5:
        gen1_ID = arr_test[4]
    if  len(arr_test) >=6:
        gen2_ID = arr_test[5]
    if  len(arr_test) >=7:
        gen3_ID = arr_test[6]
    if  len(arr_test) >=8:
        gen4_ID = arr_test[7]
    if  len(arr_test) >=9:
        gen5_ID = arr_test[8]
    if  len(arr_test) >=10:
        gen6_ID = arr_test[9]
    if  len(arr_test) >=11:
        gen7_ID = arr_test[10]

    if userID!= lastUserID:
        ii=0
        user_rating_inTrain=numpy.zeros(shape=(6,9))

    trackID_vec[ii]=trackID
    albumID_vec[ii]=albumID
    artistID_vec[ii]=artistID
    
    gen1_vec[ii]=gen1_ID
    gen2_vec[ii]=gen2_ID
    gen3_vec[ii]=gen3_ID
    gen4_vec[ii]=gen4_ID
    gen5_vec[ii]=gen5_ID
    gen6_vec[ii]=gen6_ID
    gen7_vec[ii]=gen7_ID
    
    ii=ii+1
    lastUserID=userID
    
    if ii==6 : 
        print(trackID_vec)
        print(albumID_vec)
        print(artistID_vec)
        print(gen1_vec)
        print(gen2_vec)
        print(gen3_vec)
        print(gen4_vec)
        print(gen5_vec)
        print(gen6_vec)
        print(gen7_vec)
        while (Trainline):
            # for Trainline in fTrain:
            arr_train = Trainline.strip().split('|')
            trainUserID=arr_train[0]
            trainItemID=arr_train[1]
            trainRating=arr_train[2]
            Trainline=fTrain.readline()

            if trainUserID< userID:
                continue
            if trainUserID== userID:
                for nn in range(0, 6):
                    if trainItemID==albumID_vec[nn]:
                        user_rating_inTrain[nn, 0]=trainRating
                    if trainItemID==artistID_vec[nn]:
                        user_rating_inTrain[nn, 1]=trainRating
                        
                    if trainItemID==gen1_vec[nn]:
                        user_rating_inTrain[nn, 2]=trainRating
                    if trainItemID==gen2_vec[nn]:
                        user_rating_inTrain[nn, 3]=trainRating
                    if trainItemID==gen3_vec[nn]:
                        user_rating_inTrain[nn, 4]=trainRating
                    if trainItemID==gen4_vec[nn]:
                        user_rating_inTrain[nn, 5]=trainRating
                    if trainItemID==gen5_vec[nn]:
                        user_rating_inTrain[nn, 6]=trainRating
                    if trainItemID==gen6_vec[nn]:
                        user_rating_inTrain[nn, 7]=trainRating
                    if trainItemID==gen7_vec[nn]:
                        user_rating_inTrain[nn, 8]=trainRating
            if trainUserID> userID:
                user_rating_inTrain = user_rating_inTrain + 100
                print(user_rating_inTrain)
                for nn in range(0, 6):
                    outStr=str(userID) + '|' + str(trackID_vec[nn])+ '|' + str(user_rating_inTrain[nn,0]) + '|' + str(user_rating_inTrain[nn, 1]) + '|' + str(user_rating_inTrain[nn, 2])+ '|' + str(user_rating_inTrain[nn, 3])+ '|' + str(user_rating_inTrain[nn, 4])+ str(user_rating_inTrain[nn, 5])+ '|' + str(user_rating_inTrain[nn, 6])+ '|' + str(user_rating_inTrain[nn, 7])+ '|' + str(user_rating_inTrain[nn, 8])
                    fOut.write(outStr + '\n')
                break
    if(userID == '199813'):
        break

fTest.close()
fTrain.close()
fOut.close()

['208019', '74139', '9903', '242681', '18515', '105760']
['209288', '277282', 'None', '190640', '146344', '93458']
['None', '271146', 'None', '244574', '33168', '11616']
[0, '113360', '33722', '61215', '19913', '131552']
[0, '173467', '123396', '17453', '48505', '173467']
[0, '173655', '79926', '274088', '154024', '48505']
[0, '192976', '73523', 0, 0, '133159']
[0, '146792', 0, 0, 0, 0]
[0, '48505', 0, 0, 0, 0]
[0, '133159', 0, 0, 0, 0]
[[100. 100. 100. 100. 100. 100. 100. 100. 100.]
 [100. 100. 100. 180. 100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100. 100. 100. 100. 100.]
 [100. 100. 100. 100. 100. 100. 100. 100. 100.]
 [100. 170. 100. 100. 100. 100. 100. 100. 100.]
 [100. 190. 180. 180. 100. 100. 100. 100. 100.]]
['276940', '142408', '130023', '29189', '223706', '211361']
['201356', '112725', '226816', '104694', '101750', '127464']
['163237', '275191', '275191', '211701', '128069', '19438']
['287681', '158282', '158282', '158282', '158282', '77904']
[0, '173467', '242383', '1734

In [7]:
import pandas as pd

output=pd.read_csv('output1.txt',sep='|',header=None)

output.columns=['User ID','Track ID','Album Rating','Artist Rating']
output['Sum']=output[['Album Rating','Artist Rating']].sum(axis=1)

train_df=pd.read_csv('trainIdx2_matrix.txt', sep='|',header=None)
train_df.columns=['trainUserID','trainItemID','trainRating']


output_cp=output.copy()
output_cp['Predictor']=0

output_cp['Predictor'][output_cp[0:6]['Sum'].nlargest(3).index]=1


start=0
for i in range(20000):
    output_cp['Predictor'][output_cp[start:6*(i+1)]['Sum'].nlargest(3).index]=1
    start=6*(i+1)

output_cp_ans= output_cp[['User ID', 'Track ID','Predictor']]
output_cp_ans['Track ID']=output_cp_ans['User ID'].astype(str) +'_'+ output_cp_ans['Track ID'].astype(str)
output_cp_ans.drop(columns={'User ID'},inplace=True)
output_cp_ans.to_csv('sum.csv', index=False)

C:\Users\psahu\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
